pull_request_rules:
  - name: Merge Dependabot PRs on approval with [skip ci]
    conditions:
      - "#approved-reviews-by>=1"
      - or:
          - author=dependabot[bot]
          - author=github-actions[bot]
    actions:
      merge:
        method: merge
        commit_message_template: |
          {{ title | markdownify }} [skip ci]
          {{ body | markdownify }}
queue_rules: []
