CREATE VERTEX TYPE Link IF NOT EXISTS;

CREATE PROPERTY Link.url IF NOT EXISTS STRING (
    MANDATORY TRUE,
    NOTNULL TRUE
  );
CREATE INDEX IF NOT EXISTS ON Link (url) UNIQUE;

CREATE PROPERTY Link.id IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX ON Link (id) UNIQUE;

CREATE PROPERTY Link.title IF NOT EXISTS STRING ;
CREATE PROPERTY Link.description IF NOT EXISTS  STRING;
CREATE PROPERTY Link.extractedAt IF NOT EXISTS LONG;
CREATE PROPERTY Link.contentType IF NOT EXISTS STRING;

CREATE EDGE TYPE LinkConnection IF NOT EXISTS;
