CREATE VERTEX TYPE Link IF NOT EXISTS;

CREATE PROPERTY Link.url IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX IF NOT EXISTS ON Link (url) UNIQUE;

CREATE PROPERTY Link.id IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX ON Link (id) UNIQUE;

CREATE PROPERTY Link.title IF NOT EXISTS STRING;
CREATE PROPERTY Link.description IF NOT EXISTS STRING;
CREATE PROPERTY Link.extractedAt IF NOT EXISTS DATETIME;
CREATE PROPERTY Link.contentType IF NOT EXISTS STRING;

CREATE EDGE TYPE IsLinkedTo IF NOT EXISTS;
CREATE PROPERTY IsLinkedTo.in LINK OF Link;
CREATE PROPERTY IsLinkedTo.out LINK OF Link;

CREATE VERTEX TYPE Content IF NOT EXISTS;
CREATE PROPERTY Content.id IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX IF NOT EXISTS ON Content (id) UNIQUE;
CREATE PROPERTY Content.title IF NOT EXISTS STRING;
CREATE PROPERTY Content.summary IF NOT EXISTS STRING;
CREATE PROPERTY Content.text IF NOT EXISTS STRING;
CREATE PROPERTY Content.extractedAt IF NOT EXISTS DATETIME;

CREATE EDGE TYPE HasContent IF NOT EXISTS;
CREATE PROPERTY HasContent.in LINK OF Link;
CREATE PROPERTY HasContent.out LINK OF Content;
