-- Create Link vertex type
CREATE VERTEX TYPE Link;
CREATE PROPERTY Link.id STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Link.url STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Link.title STRING;
CREATE PROPERTY Link.description STRING;
CREATE PROPERTY Link.extractedAt DATETIME_SECOND;
CREATE PROPERTY Link.contentType STRING;

-- Create indexes for Link
CREATE INDEX ON Link(id) UNIQUE;
CREATE INDEX ON Link(url) UNIQUE;
CREATE INDEX ON Link(extractedAt) NOTUNIQUE;
