-- Create Link vertex type
CREATE VERTEX TYPE Link IF NOT EXISTS;
CREATE PROPERTY Link.id IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Link.url IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Link.title IF NOT EXISTS STRING;
CREATE PROPERTY Link.description IF NOT EXISTS STRING;
CREATE PROPERTY Link.extractedAt IF NOT EXISTS DATETIME_SECOND;
CREATE PROPERTY Link.contentType IF NOT EXISTS STRING;

-- Create indexes for Link
CREATE INDEX IF NOT EXISTS ON Link(id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Link(url) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Link(extractedAt) NOTUNIQUE;
