-- Create User vertex type
CREATE VERTEX TYPE User;
CREATE PROPERTY User.id STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.username STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.email STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.passwordHash STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.salt STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.createdAt DATETIME_SECOND (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.updatedAt DATETIME_SECOND;
CREATE PROPERTY User.isActive BOOLEAN (MANDATORY TRUE, NOTNULL TRUE, DEFAULT true);
CREATE PROPERTY User.firstName STRING;
CREATE PROPERTY User.lastName STRING;
CREATE PROPERTY User.lastLoginAt DATETIME_SECOND;

-- Create indexes for User
CREATE INDEX ON User(id) UNIQUE;
CREATE INDEX ON User(username) UNIQUE;
CREATE INDEX ON User(email) UNIQUE;
CREATE INDEX ON User(email, isActive) NOTUNIQUE;
CREATE INDEX ON User(username, isActive) NOTUNIQUE;
CREATE INDEX ON User(isActive) NOTUNIQUE;

-- Create AuthToken vertex type for refresh token management
CREATE VERTEX TYPE AuthToken;
CREATE PROPERTY AuthToken.id STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.token STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.tokenType STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.userId STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.createdAt DATETIME_SECOND (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.expiresAt DATETIME_SECOND (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.usedAt DATETIME_SECOND;
CREATE PROPERTY AuthToken.isRevoked BOOLEAN (MANDATORY TRUE, NOTNULL TRUE, DEFAULT false);
CREATE PROPERTY AuthToken.ipAddress STRING;
CREATE PROPERTY AuthToken.userAgent STRING;

-- Create indexes for AuthToken
CREATE INDEX ON AuthToken(id) UNIQUE;
CREATE INDEX ON AuthToken(token) UNIQUE;
CREATE INDEX ON AuthToken(userId) NOTUNIQUE;
CREATE INDEX ON AuthToken(tokenType) NOTUNIQUE;
CREATE INDEX ON AuthToken(expiresAt) NOTUNIQUE;
CREATE INDEX ON AuthToken(token, isRevoked) NOTUNIQUE;
CREATE INDEX ON AuthToken(userId, tokenType, isRevoked) NOTUNIQUE;
CREATE INDEX ON AuthToken(expiresAt, isRevoked) NOTUNIQUE;
CREATE INDEX ON AuthToken(tokenType, expiresAt) NOTUNIQUE;

-- Create edge relationships
CREATE EDGE TYPE HasToken;
CREATE PROPERTY HasToken.in LINK OF User;
CREATE PROPERTY HasToken.out LINK OF AuthToken;
