-- Create User vertex type
CREATE VERTEX TYPE User IF NOT EXISTS;
CREATE PROPERTY User.id IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.username IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.email IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.passwordHash IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.salt IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.createdAt IF NOT EXISTS DATETIME_SECOND (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.updatedAt IF NOT EXISTS DATETIME_SECOND;
CREATE PROPERTY User.isActive IF NOT EXISTS BOOLEAN (MANDATORY TRUE, NOTNULL TRUE, DEFAULT true);
CREATE PROPERTY User.firstName IF NOT EXISTS STRING;
CREATE PROPERTY User.lastName IF NOT EXISTS STRING;
CREATE PROPERTY User.lastLoginAt IF NOT EXISTS DATETIME_SECOND;

-- Create indexes for User
CREATE INDEX IF NOT EXISTS ON User(id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON User(username) UNIQUE;
CREATE INDEX IF NOT EXISTS ON User(email) UNIQUE;
CREATE INDEX IF NOT EXISTS ON User(email, isActive) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON User(username, isActive) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON User(isActive) NOTUNIQUE;

-- Create AuthToken vertex type for refresh token management
CREATE VERTEX TYPE AuthToken IF NOT EXISTS;
CREATE PROPERTY AuthToken.id IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.token IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.tokenType IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.userId IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.createdAt IF NOT EXISTS DATETIME_SECOND (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.expiresAt IF NOT EXISTS DATETIME_SECOND (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY AuthToken.usedAt IF NOT EXISTS DATETIME_SECOND;
CREATE PROPERTY AuthToken.isRevoked IF NOT EXISTS BOOLEAN (MANDATORY TRUE, NOTNULL TRUE, DEFAULT false);
CREATE PROPERTY AuthToken.ipAddress IF NOT EXISTS STRING;
CREATE PROPERTY AuthToken.userAgent IF NOT EXISTS STRING;

-- Create indexes for AuthToken
CREATE INDEX IF NOT EXISTS ON AuthToken(id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON AuthToken(token) UNIQUE;
CREATE INDEX IF NOT EXISTS ON AuthToken(userId) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON AuthToken(tokenType) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON AuthToken(expiresAt) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON AuthToken(token, isRevoked) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON AuthToken(userId, tokenType, isRevoked) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON AuthToken(expiresAt, isRevoked) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON AuthToken(tokenType, expiresAt) NOTUNIQUE;

-- Create edge relationships
CREATE EDGE TYPE HasToken IF NOT EXISTS;
CREATE PROPERTY HasToken.in IF NOT EXISTS LINK OF User;
CREATE PROPERTY HasToken.out IF NOT EXISTS LINK OF AuthToken;
