-- Create Role vertex type for authorization
CREATE VERTEX TYPE Role IF NOT EXISTS;
CREATE PROPERTY Role.id IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Role.name IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Role.description IF NOT EXISTS STRING;
CREATE PROPERTY Role.permissions IF NOT EXISTS LIST OF STRING;
CREATE PROPERTY Role.isActive IF NOT EXISTS BOOLEAN (MANDATORY TRUE, NOTNULL TRUE, DEFAULT true);

-- Create indexes for Role
CREATE INDEX IF NOT EXISTS ON Role(id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Role(name) UNIQUE;

-- Create edge relationships between User and Link
CREATE EDGE TYPE OwnsLink IF NOT EXISTS;
CREATE PROPERTY OwnsLink.in IF NOT EXISTS LINK OF User;
CREATE PROPERTY OwnsLink.out IF NOT EXISTS LINK OF Link;
CREATE PROPERTY OwnsLink.createdAt IF NOT EXISTS DATETIME_SECOND (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY OwnsLink.accessLevel IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE, DEFAULT 'OWNER');

-- Create edge relationships between User and Role
CREATE EDGE TYPE HasRole IF NOT EXISTS;
CREATE PROPERTY HasRole.in IF NOT EXISTS LINK OF User;
CREATE PROPERTY HasRole.out IF NOT EXISTS LINK OF Role;
CREATE PROPERTY HasRole.assignedAt IF NOT EXISTS DATETIME_SECOND (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY HasRole.assignedBy IF NOT EXISTS STRING;

-- Create indexes for edge relationships
CREATE INDEX IF NOT EXISTS ON OwnsLink(accessLevel) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON OwnsLink(accessLevel, createdAt) NOTUNIQUE;
