-- Create Content vertex type
CREATE VERTEX TYPE Content IF NOT EXISTS;

-- Create properties for Content
CREATE PROPERTY Content.id IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Content.linkId IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Content.htmlContent IF NOT EXISTS STRING;
CREATE PROPERTY Content.textContent IF NOT EXISTS STRING;
CREATE PROPERTY Content.contentLength IF NOT EXISTS INTEGER;
CREATE PROPERTY Content.downloadedAt IF NOT EXISTS DATETIME_SECOND;
CREATE PROPERTY Content.mimeType IF NOT EXISTS STRING;
CREATE PROPERTY Content.status IF NOT EXISTS STRING;

-- Create indexes for Content
CREATE INDEX IF NOT EXISTS ON Content (id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Content (linkId) UNIQUE;

-- Create HasContent edge type
CREATE EDGE TYPE HasContent IF NOT EXISTS;

-- Create properties for HasContent edge
CREATE PROPERTY HasContent.createdAt IF NOT EXISTS DATETIME_SECOND;
