CREATE VERTEX TYPE Collection IF NOT EXISTS;
CREATE PROPERTY Collection.id IF NOT EXISTS STRING;
CREATE PROPERTY Collection.name IF NOT EXISTS STRING;
CREATE PROPERTY Collection.description IF NOT EXISTS STRING;
CREATE PROPERTY Collection.userId IF NOT EXISTS STRING;
CREATE PROPERTY Collection.query IF NOT EXISTS STRING;
CREATE INDEX IF NOT EXISTS ON Collection (id) UNIQUE;

CREATE VERTEX TYPE Domain IF NOT EXISTS;
CREATE PROPERTY Domain.name IF NOT EXISTS STRING;
CREATE INDEX IF NOT EXISTS ON Domain (name) UNIQUE;

CREATE VERTEX TYPE Tag IF NOT EXISTS;
CREATE PROPERTY Tag.name IF NOT EXISTS STRING;
CREATE INDEX IF NOT EXISTS ON Tag (name) UNIQUE;

CREATE EDGE TYPE belongsToDomain IF NOT EXISTS;
CREATE EDGE TYPE hasTag IF NOT EXISTS;
CREATE EDGE TYPE inCollection IF NOT EXISTS;
CREATE EDGE TYPE ContainsLink IF NOT EXISTS;
CREATE PROPERTY ContainsLink.addedAt IF NOT EXISTS DATETIME_SECOND;
