CREATE VERTEX TYPE Collection;
CREATE PROPERTY Collection.id STRING;
CREATE PROPERTY Collection.name STRING;
CREATE PROPERTY Collection.description STRING;
CREATE PROPERTY Collection.userId STRING;
CREATE PROPERTY Collection.query STRING;
CREATE INDEX ON Collection (id) UNIQUE;

CREATE VERTEX TYPE Domain;
CREATE PROPERTY Domain.name STRING;
CREATE INDEX ON Domain (name) UNIQUE;

CREATE VERTEX TYPE Tag;
CREATE PROPERTY Tag.name STRING;
CREATE INDEX ON Tag (name) UNIQUE;

CREATE EDGE TYPE BELONGS_TO_DOMAIN;
CREATE EDGE TYPE HAS_TAG;
CREATE EDGE TYPE IN_COLLECTION;
