CREATE VERTEX TYPE Note IF NOT EXISTS;
CREATE PROPERTY Note.id IF NOT EXISTS STRING;
CREATE PROPERTY Note.linkId IF NOT EXISTS STRING;
CREATE PROPERTY Note.userId IF NOT EXISTS STRING;
CREATE PROPERTY Note.content IF NOT EXISTS STRING;
CREATE PROPERTY Note.createdAt IF NOT EXISTS DATETIME_SECOND;
CREATE PROPERTY Note.updatedAt IF NOT EXISTS DATETIME_SECOND;
CREATE INDEX IF NOT EXISTS ON Note (id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Note (linkId, userId) NOTUNIQUE;
