-- Add link status tracking fields (LINA-5)
CREATE PROPERTY Link.readStatus IF NOT EXISTS STRING;
CREATE PROPERTY Link.archived IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Link.favorited IF NOT EXISTS BOOLEAN;
CREATE INDEX IF NOT EXISTS ON Link (readStatus) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON Link (archived) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON Link (favorited) NOTUNIQUE;
