-- Create Tag vertex type (LINA-4)
CREATE VERTEX TYPE Tag IF NOT EXISTS;
CREATE PROPERTY Tag.id IF NOT EXISTS STRING;
CREATE PROPERTY Tag.name IF NOT EXISTS STRING;
CREATE PROPERTY Tag.userId IF NOT EXISTS STRING;
CREATE PROPERTY Tag.createdAt IF NOT EXISTS DATETIME_SECOND;
CREATE INDEX IF NOT EXISTS ON Tag (id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Tag (name, userId) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Tag (userId) NOTUNIQUE;

-- Create HasTag edge type connecting Link -> Tag
CREATE EDGE TYPE HasTag IF NOT EXISTS;
