CREATE VERTEX TYPE Content IF NOT EXISTS;
CREATE PROPERTY Content.id IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX IF NOT EXISTS ON Content (id) UNIQUE;
CREATE PROPERTY Content.title IF NOT EXISTS STRING;
CREATE PROPERTY Content.summary IF NOT EXISTS STRING;
CREATE PROPERTY Content.text IF NOT EXISTS STRING;
CREATE PROPERTY Content.extractedAt IF NOT EXISTS DATETIME_SECOND;

CREATE EDGE TYPE HasContent IF NOT EXISTS;
CREATE PROPERTY HasContent.in LINK OF Link;
CREATE PROPERTY HasContent.out LINK OF Content;
